# Generated by Django 5.2.6 on 2025-09-22 18:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcondominio', '0003_delete_task_alter_rol_options_rol_is_system_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torre', models.CharField(max_length=100)),
                ('bloque', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(max_length=20)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('DEP', 'Departamento'), ('CASA', 'Casa'), ('LOCAL', 'Local')], max_length=20)),
                ('metraje', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('coeficiente', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('dormitorios', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('parqueos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bodegas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('OCUPADA', 'Ocupada'), ('DESOCUPADA', 'Desocupada'), ('MANTENIMIENTO', 'Mantenimiento'), ('INACTIVA', 'Inactiva')], default='DESOCUPADA', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades', to=settings.AUTH_USER_MODEL)),
                ('residente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['torre', 'bloque', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('torre', 'bloque', 'numero'), name='uniq_unidad_torre_bloque_numero')],
            },
        ),
    ]
