# Generated by Django 5.2.6 on 2025-09-22 20:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcondominio', '0004_unidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7)),
                ('concepto', models.CharField(default='GASTO_COMUN', max_length=50)),
                ('monto_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('usa_coeficiente', models.BooleanField(default=True)),
                ('coeficiente_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('monto_calculado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('mora_aplicada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='smartcondominio.unidad')),
            ],
            options={
                'ordering': ['-periodo', 'unidad_id'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medio', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('valido', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_cargados', to=settings.AUTH_USER_MODEL)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='smartcondominio.cuota')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['periodo', 'concepto'], name='smartcondom_periodo_97cb07_idx'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('unidad', 'periodo', 'concepto'), name='uniq_cuota_unidad_periodo_concepto_activa'),
        ),
    ]
