# Generated by Django 5.2.6 on 2025-09-23 01:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcondominio', '0005_cuota_pago_cuota_smartcondom_periodo_97cb07_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('RUIDO', 'Ruido'), ('MASCOTA', 'Mascota'), ('ESTACIONAMIENTO', 'Estacionamiento indebido'), ('DANOS', 'Daños'), ('OTRA', 'Otra')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('evidencia_url', models.URLField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESUELTA', 'Resuelta'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infracciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('residente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infracciones', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='infracciones', to='smartcondominio.unidad')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
