# Generated by Django 5.2.6 on 2025-09-24 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcondominio', '0006_infraccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('audiencia', models.CharField(choices=[('ALL', 'Todos'), ('TORRE', 'Por torre'), ('UNIDAD', 'Por unidad'), ('ROL', 'Por rol')], default='ALL', max_length=10)),
                ('torre', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PROGRAMADO', 'Programado'), ('PUBLICADO', 'Publicado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=12)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notify_inapp', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=False)),
                ('notify_push', models.BooleanField(default=False)),
                ('adjuntos', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_creados', to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(blank=True, to='smartcondominio.rol')),
                ('unidades', models.ManyToManyField(blank=True, to='smartcondominio.unidad')),
            ],
            options={
                'ordering': ['-publish_at', '-created_at'],
                'indexes': [models.Index(fields=['audiencia', 'status'], name='smartcondom_audienc_1a1717_idx'), models.Index(fields=['publish_at'], name='smartcondom_publish_6dc000_idx')],
            },
        ),
    ]
