# Generated by Django 5.2.6 on 2025-09-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcondominio', '0008_tarea_tareacomentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['-updated_at', '-created_at'], 'permissions': [('manage_tasks', 'Puede gestionar y asignar tareas')]},
        ),
    ]
