# Generated by Django 5.2.6 on 2025-09-25 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcondominio', '0009_alter_tarea_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(blank=True, max_length=120)),
                ('capacidad', models.PositiveIntegerField(default=1)),
                ('costo_por_hora', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
                ('requiere_aprobacion', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Área Común',
                'verbose_name_plural': 'Áreas Comunes',
            },
        ),
        migrations.CreateModel(
            name='AreaDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.SmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('max_horas_por_reserva', models.PositiveIntegerField(default=4)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='smartcondominio.areacomun')),
            ],
            options={
                'ordering': ['area', 'dia_semana', 'hora_inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='area_disp_hora_fin_gt_inicio'), models.UniqueConstraint(fields=('area', 'dia_semana', 'hora_inicio', 'hora_fin'), name='area_disp_uniq_window')],
            },
        ),
        migrations.CreateModel(
            name='ReservaArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=12)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nota', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='smartcondominio.areacomun')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_area', to='smartcondominio.unidad')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_area', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['area', 'fecha_inicio', 'fecha_fin'], name='smartcondom_area_id_db01d1_idx'), models.Index(fields=['estado'], name='smartcondom_estado_934824_idx')],
            },
        ),
    ]
