# Generated by Django 5.2.6 on 2025-09-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcondominio', '0010_areacomun_areadisponibilidad_reservaarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='base',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('RESIDENT', 'Resident')], default='STAFF', max_length=10),
        ),
    ]
