# Generated by Django 5.2.6 on 2025-09-27 02:40

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcondominio', '0012_staffkind_profile_staff_kind_text_profile_staff_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidad',
            options={'ordering': ['manzana', 'lote', 'numero']},
        ),
        migrations.RemoveConstraint(
            model_name='unidad',
            name='uniq_unidad_torre_bloque_numero',
        ),
        migrations.RenameField(
            model_name='unidad',
            old_name='torre',
            new_name='manzana',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='bloque',
        ),
        migrations.AddField(
            model_name='unidad',
            name='lote',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='coeficiente',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='metraje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='tipo',
            field=models.CharField(choices=[('DEP', 'Departamento'), ('CASA', 'Casa'), ('LOCAL', 'Local')], default='CASA', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='unidad',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('manzana', 'lote', 'numero'), name='uniq_unidad_manzana_lote_numero_active'),
        ),
    ]
