# Generated by Django 5.2.6 on 2025-09-27 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcondominio', '0013_alter_unidad_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('doc_type', models.CharField(choices=[('CI', 'Cédula'), ('PASS', 'Pasaporte'), ('OTRO', 'Otro')], default='CI', max_length=10)),
                ('doc_number', models.CharField(db_index=True, max_length=40)),
                ('phone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'unique_together': {('doc_type', 'doc_number')},
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.CharField(blank=True, db_index=True, max_length=15)),
                ('purpose', models.CharField(blank=True, max_length=140)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('INGRESADO', 'Ingresado'), ('SALIDO', 'Salido'), ('CANCELADO', 'Cancelado'), ('DENEGADO', 'Denegado')], db_index=True, default='REGISTRADO', max_length=12)),
                ('entry_at', models.DateTimeField(blank=True, null=True)),
                ('exit_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits_created', to=settings.AUTH_USER_MODEL)),
                ('entry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits_entry_by', to=settings.AUTH_USER_MODEL)),
                ('exit_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits_exit_by', to=settings.AUTH_USER_MODEL)),
                ('host_resident', models.ForeignKey(help_text='Residente/anfitrión de la unidad', on_delete=django.db.models.deletion.PROTECT, related_name='hosted_visits', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='smartcondominio.unidad')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits_updated', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='smartcondominio.visitor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='smartcondom_status_25fa26_idx'), models.Index(fields=['vehicle_plate'], name='smartcondom_vehicle_b8a101_idx'), models.Index(fields=['created_at'], name='smartcondom_created_188411_idx')],
            },
        ),
    ]
