# Generated by Django 5.2.6 on 2025-09-27 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcondominio', '0014_visitor_visit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BOB', max_length=10)),
                ('provider', models.CharField(choices=[('MOCK', 'Mock')], default='MOCK', max_length=10)),
                ('provider_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('CREATED', 'Creada'), ('PENDING', 'Pendiente'), ('PAID', 'Pagada'), ('FAILED', 'Fallida'), ('CANCELLED', 'Cancelada')], default='CREATED', max_length=12)),
                ('confirmation_url', models.URLField(blank=True)),
                ('qr_payload', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentos_online', to='smartcondominio.cuota')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_url', models.URLField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('bank_name', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='smartcondominio.onlinepaymentintent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='onlinepaymentintent',
            index=models.Index(fields=['status'], name='smartcondom_status_7b65d3_idx'),
        ),
        migrations.AddIndex(
            model_name='onlinepaymentintent',
            index=models.Index(fields=['created_at'], name='smartcondom_created_3a7495_idx'),
        ),
        migrations.AddIndex(
            model_name='onlinepaymentintent',
            index=models.Index(fields=['provider_id'], name='smartcondom_provide_7667e8_idx'),
        ),
        migrations.AddIndex(
            model_name='mockreceipt',
            index=models.Index(fields=['created_at'], name='smartcondom_created_c056fc_idx'),
        ),
    ]
