# Generated by Django 5.2.6 on 2025-09-27 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcondominio', '0014_visitor_visit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(db_index=True, max_length=15, unique=True)),
                ('marca', models.CharField(blank=True, default='', max_length=40)),
                ('modelo', models.CharField(blank=True, default='', max_length=40)),
                ('color', models.CharField(blank=True, default='', max_length=30)),
                ('tipo', models.CharField(choices=[('AUTO', 'Auto'), ('MOTO', 'Moto'), ('CAMIONETA', 'Camioneta'), ('OTRO', 'Otro')], default='AUTO', max_length=12)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='vehiculos/fotos/')),
                ('activo', models.BooleanField(default=True)),
                ('autorizado_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='smartcondominio.unidad')),
            ],
            options={
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15)),
                ('marca', models.CharField(blank=True, default='', max_length=40)),
                ('modelo', models.CharField(blank=True, default='', max_length=40)),
                ('color', models.CharField(blank=True, default='', max_length=30)),
                ('tipo', models.CharField(choices=[('AUTO', 'Auto'), ('MOTO', 'Moto'), ('CAMIONETA', 'Camioneta'), ('OTRO', 'Otro')], default='AUTO', max_length=12)),
                ('foto_placa', models.ImageField(blank=True, null=True, upload_to='vehiculos/placas/')),
                ('documento', models.FileField(blank=True, null=True, upload_to='vehiculos/docs/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDIENTE', max_length=12)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_vehiculo_revisadas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_vehiculo', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_vehiculo', to='smartcondominio.unidad')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='smartcondominio.vehiculo')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['placa', 'estado'], name='smartcondom_placa_1110eb_idx')],
            },
        ),
    ]
