# Generated by Django 5.2.6 on 2025-09-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcondominio', '0015_onlinepaymentintent_mockreceipt_and_more'),
        ('smartcondominio', '0015_vehiculo_solicitudvehiculo'),
    ]

    operations = [
    ]
