# Generated by Django 5.2.6 on 2025-09-28 05:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcondominio', '0016_merge_20250927_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='coeficiente_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
    ]
