# Generated by Django 5.2.6 on 2025-09-28 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcondominio', '0017_alter_cuota_coeficiente_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera_id', models.CharField(blank=True, max_length=60)),
                ('plate_raw', models.CharField(blank=True, max_length=30)),
                ('plate_norm', models.CharField(blank=True, db_index=True, max_length=30)),
                ('score', models.FloatField(blank=True, null=True)),
                ('decision', models.CharField(max_length=32)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('opened', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartcondominio.vehiculo')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartcondominio.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
