# Generated by Django 5.2.6 on 2025-09-28 23:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcondominio', '0018_accessevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='approval_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='approval_status',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('APR', 'Aprobada'), ('DEN', 'Denegada'), ('EXP', 'Expirada')], db_index=True, default='PEND', max_length=4),
        ),
        migrations.AddField(
            model_name='visit',
            name='approval_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='denied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='denied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_denied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['approval_status'], name='smartcondom_approva_040acb_idx'),
        ),
    ]
