# Generated by Django 5.2.6 on 2025-09-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcondominio', '0019_visit_approval_expires_at_visit_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockreceipt',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
