# Generated by Django 5.2.6 on 2025-09-29 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcondominio', '0020_mockreceipt_receipt_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_reportado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medio', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('OTRO', 'Otro')], default='TRANSFERENCIA', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('nota', models.TextField(blank=True)),
                ('receipt_url', models.URLField(blank=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='PENDIENTE', max_length=12)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('razon_rechazo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='smartcondominio.cuota')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desde_comprobante', to='smartcondominio.pago')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_enviados', to=settings.AUTH_USER_MODEL)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estado'], name='smartcondom_estado_d2b839_idx'), models.Index(fields=['created_at'], name='smartcondom_created_57ea5d_idx')],
            },
        ),
    ]
