# Generated by Django 5.2.6 on 2025-09-30 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcondominio', '0021_pagocomprobante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aviso',
            name='smartcondom_audienc_1a1717_idx',
        ),
        migrations.RemoveIndex(
            model_name='aviso',
            name='smartcondom_publish_6dc000_idx',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='adjuntos',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='audiencia',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='notify_email',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='notify_inapp',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='notify_push',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='torre',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='unidades',
        ),
        migrations.AddField(
            model_name='aviso',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='publish_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='status',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('ARCHIVADO', 'Archivado')], db_index=True, default='BORRADOR', max_length=12),
        ),
    ]
