# Generated by Django 5.2.6 on 2025-09-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcondominio', '0022_remove_aviso_smartcondom_audienc_1a1717_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessevent',
            name='direction',
            field=models.CharField(blank=True, choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], db_index=True, max_length=10),
        ),
    ]
