# Generated by Django 5.2.6 on 2025-09-30 06:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcondominio', '0023_accessevent_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceAccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('camera_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('direction', models.CharField(blank=True, choices=[('ENTRADA', 'ENTRADA'), ('SALIDA', 'SALIDA'), ('', 'No especificado')], db_index=True, default='', max_length=10)),
                ('decision', models.CharField(choices=[('ALLOW_RESIDENT', 'ALLOW_RESIDENT'), ('ALLOW_VISIT', 'ALLOW_VISIT'), ('DENY_UNKNOWN', 'DENY_UNKNOWN'), ('ERROR_OCR', 'ERROR_OCR')], db_index=True, max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('opened', models.BooleanField(default=False)),
                ('snapshot', models.FileField(blank=True, null=True, upload_to='face_snapshots/')),
                ('reason', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('matched_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_events', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_events_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
